/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type EventStatus = "cancelled" | "draft" | "published";

export type FriendshipStatus = "accepted" | "blocked" | "pending" | "rejected";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type MembershipType = "editor" | "owner";

export type ReportStatus = "pending" | "rejected" | "resolved" | "reviewed";

export type Timestamp = ColumnType<Date, Date | string>;

export interface Alternateorgnames {
  alternate_name: string;
  alternate_name_id: Generated<number>;
  org_id: number;
}

export interface Blocks {
  blocked_id: number;
  date_created: Generated<Timestamp>;
  user_id: number;
}

export interface Eventorgs {
  event_id: number;
  official: Generated<boolean>;
  org_id: number;
}

export interface Events {
  contributor_id: number;
  date_created: Generated<Timestamp>;
  date_modified: Generated<Timestamp>;
  end_time: Timestamp | null;
  event_description: string | null;
  event_id: Generated<number>;
  event_img: string | null;
  event_location: string | null;
  event_name: string | null;
  event_saves: Generated<number>;
  event_status: EventStatus;
  max_capacity: number | null;
  start_time: Timestamp | null;
}

export interface Eventtags {
  event_id: number;
  tag_id: number;
}

export interface Feedback {
  date_created: Generated<Timestamp>;
  email: string | null;
  feedback_id: Generated<number>;
  feedback_type: string;
  message: string;
  name: string | null;
}

export interface Friendships {
  date_created: Generated<Timestamp>;
  status: Generated<FriendshipStatus | null>;
  user1_id: number;
  user2_id: number;
}

export interface Orgs {
  org_building: string | null;
  org_description: string | null;
  org_email: string | null;
  org_events_count: Generated<number>;
  org_icon: string | null;
  org_id: Generated<number>;
  org_members_count: Generated<number>;
  org_name: string;
  org_reputation: Generated<number>;
  org_room: string | null;
  org_verified: Generated<boolean>;
}

export interface Orgslugs {
  org_id: number;
  org_slug: string;
}

export interface Orgtags {
  org_id: number;
  tag_id: number;
}

export interface Reports {
  admin_notes: string | null;
  date_created: Generated<Timestamp>;
  date_modified: Generated<Timestamp>;
  report_id: Generated<number>;
  report_reason: string;
  report_status: Generated<ReportStatus>;
  reported_event_id: number | null;
  reported_org_id: number | null;
  reporter_user_id: number | null;
  resolution_date: Timestamp | null;
}

export interface Savedevents {
  date_created: Generated<Timestamp>;
  event_id: number;
  user_id: number;
}

export interface Tags {
  tag_description: string | null;
  tag_id: Generated<number>;
  tag_name: string;
  tag_official: Generated<boolean>;
}

export interface Userattendance {
  date_created: Generated<Timestamp>;
  event_id: number;
  user_id: number;
}

export interface Userfollows {
  date_created: Generated<Timestamp>;
  org_id: number;
  user_id: number;
}

export interface Userorgs {
  date_created: Generated<Timestamp>;
  date_modified: Generated<Timestamp>;
  org_id: number;
  user_id: number;
  user_role: MembershipType | null;
}

export interface Users {
  user_banned: Generated<boolean>;
  user_description: string | null;
  user_displayname: string;
  user_email: string;
  user_id: Generated<number>;
  user_major: string | null;
  user_mod: Generated<boolean>;
  user_name: string | null;
  user_profile_img: string | null;
  user_saved_events: Generated<number>;
  user_verified: Generated<boolean>;
  user_year: number | null;
}

export interface Usersubs {
  date_created: Generated<Timestamp>;
  org_id: number;
  user_id: number;
}

export interface DB {
  alternateorgnames: Alternateorgnames;
  blocks: Blocks;
  eventorgs: Eventorgs;
  events: Events;
  eventtags: Eventtags;
  feedback: Feedback;
  friendships: Friendships;
  orgs: Orgs;
  orgslugs: Orgslugs;
  orgtags: Orgtags;
  reports: Reports;
  savedevents: Savedevents;
  tags: Tags;
  userattendance: Userattendance;
  userfollows: Userfollows;
  userorgs: Userorgs;
  users: Users;
  usersubs: Usersubs;
}
