services:
  db:
    container_name: postgres_container
    image: postgres:17
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./table_create.sql:/docker-entrypoint-initdb.d/table_create.sql
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "agev"
    labels:
      - "pgbackup.enable=true"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dokploy-network
  pgbackups:
    container_name: pgbackups
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres # Optional: see below
    volumes:
        - ./pgbackups:/backups
    links:
        - db
    depends_on:
        - db
    environment:
        - POSTGRES_HOST=postgres_container
        - POSTGRES_DB=agev
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_EXTRA_OPTS=-Z1 --schema=public --blobs
        - SCHEDULE=@daily
        - BACKUP_ON_START=TRUE
        - BACKUP_KEEP_DAYS=7
        - BACKUP_KEEP_WEEKS=4
        - BACKUP_KEEP_MONTHS=6
        - HEALTHCHECK_PORT=8080
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true
