services:
  traefik:
    image: traefik:v3.1.4
    container_name: traefik
    restart: always
    ports:
      - "80:80"        # HTTP
      - "443:443"      # HTTPS
      - "8080:8080"    # Traefik dashboard (optional)
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--log.level=INFO"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entryPoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.certresolver=letsencrypt"
      - "--certificatesresolvers.letsencrypt.acme.email=zanbowie138@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"  # Store SSL certificates
    networks:
      - traefik-network
  app:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: app_container
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - frontend/.env
    depends_on:
      - backend
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`aggieevents.tech`)"  # Replace with your domain
      - "traefik.http.routers.app.entrypoints=websecure"     # HTTPS
      - "traefik.http.routers.app.tls=true"  # Enable SSL
      - "traefik.http.routers.app.tls.certresolver=letsencrypt"  # Use Let's Encrypt for SSL
    networks:
      - traefik-network
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend_container
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - backend/.env
    expose:
      - "5000"
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.aggieevents.tech`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"  # Enable SSL
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
    networks:
      - traefik-network
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "agev"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - traefik-network
networks:
  traefik-network:
    name: traefik-network
    driver: bridge  # Optional: define the network driver (default is `bridge`)
