services:
  db:
    container_name: postgres_container
    image: postgres:17
    restart: always
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
      - ./table_create.sql:/docker-entrypoint-initdb.d/table_create.sql
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "aggieevents"
      POSTGRES_DB: "agev"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports: 
      - "5050:80"
