services:
  traefik:
    image: traefik:v3.2.1
    container_name: traefik
    restart: always
    ports:
      - "80:80"        # HTTP
      - "443:443"      # HTTPS
      - "8080:8080"    # Traefik dashboard (optional)
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--log.level=INFO"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entryPoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=zanbowie138@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"  # Store SSL certificates
    networks:
      - traefik-network
  db:
    container_name: postgres_container
    image: postgres:17
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./table_create.sql:/docker-entrypoint-initdb.d/table_create.sql
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "agev"
    labels:
      - "pgbackup.enable=true"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - traefik-network
  pgbackups:
    container_name: pgbackups
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres # Optional: see below
    volumes:
        - ./pgbackups:/backups
    links:
        - db
    depends_on:
        - db
    environment:
        - POSTGRES_HOST=postgres_container
        - POSTGRES_DB=agev
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_EXTRA_OPTS=-Z1 --schema=public --blobs
        - SCHEDULE=@daily
        - BACKUP_ON_START=TRUE
        - BACKUP_KEEP_DAYS=7
        - BACKUP_KEEP_WEEKS=4
        - BACKUP_KEEP_MONTHS=6
        - HEALTHCHECK_PORT=8080
    networks:
      - traefik-network
networks:
  traefik-network:
    name: traefik-network
    driver: bridge  # Optional: define the network driver (default is `bridge`)
