services:
  app:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: app_container
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    ports:
      - "3000:3000"
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend_container
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    ports:
      - "5000:5000"
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "agev"
