services:
  app:
    image: agev/frontend:latest
    container_name: app_container
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - .env.frontend
    depends_on:
      - backend
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`aggieevents.tech`)"  # Replace with your domain
      - "traefik.http.routers.app.entrypoints=websecure"     # HTTPS
      - "traefik.http.routers.app.tls.certresolver=letsencrypt"  # Use Let's Encrypt for SSL
      - "traefik.http.services.next-app.loadbalancer.server.port=3000"
    networks:
      - dokploy-network
  backend:
    image: agev/backend:latest
    container_name: backend_container
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - .env.backend
    expose:
      - "5000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.aggieevents.tech`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.services.api.loadbalancer.server.port=5000"
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true
