services:
  app:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: app_container
    environment:
      - NODE_ENV=development
    env_file:
      - frontend/.env
    depends_on:
      - backend-api
    ports:
      - "3000:3000"
  backend-api:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend_container
    environment:
      - NODE_ENV=development
    env_file:
      - backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    container_name: postgres_container
    image: postgres
    restart: always
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "aggieevents"
      POSTGRES_DB: "agev"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports: 
      - "5050:80"
