name: Deploy to VPS

on:
  push:
    branches:
      - main


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: VPS

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: webfactory/ssh-agent@v0.9.0
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create root .env file
        run: |
          touch .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
      
      - name: Create frontend .env file
        run: |
          touch frontend/.env
          echo API_URL=${{ vars.API_URL }} >> frontend.env
          echo AUTH_URL=${{ vars.AUTH_URL }} >> frontend.env
          echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> frontend.env
          echo GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} >> frontend.env

      - name: Create backend .env file
        run: |
          touch backend/.env
          echo FRONTEND_URL=${{ vars.FRONTEND_URL }} >> backend.env
          echo BACKEND_URL=${{ vars.BACKEND_URL }} >> backend.env
          echo DATABASE_URL=${{ vars.DATABASE_URL }} >> backend.env

          echo GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} >> backend.env
          echo GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} >> backend.env
          echo BACKEND_SECRET=${{ secrets.BACKEND_SECRET }} >> backend.env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> backend.env

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Copy docker-compose.prod.yml
        run: |
          scp compose.prod.yml .env frontend.env backend.env ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }}: ~/deploy

      - name: multiple command
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/deploy
            sh run_prod.sh
      
      